### ISSUE TITLE
Better README description for DevOps

### ISSUE THREAD

**Issue by Qoyyuum** [g0x7f/devOps-patch#4]
While I applaud the use of github to share info and knowledge in the field of DevOps, it definitely needs better wording to help communicate the end users what this repo is about.

You can keep the word "patch" to the whole DevOps as your branding of this repo, but there should be description for what this repo is about.

Next, the download portion to MegaDownloader should be obvious as to what the end user will be downloading. A better alternative would be to have the users download the files directly from this repo. Add a warning to not clone this repo as it contains some X-amount of GB to successfully clone everything.

Might also add an objective as to what this repo is trying to achieve. People can contribute but we gotta contribute towards a goal that is achievable for this repo.

My two cents.

**Comment by g0x7f** [comment]
1st
Main objective to help the DevOps community Upgrading The skills-sets/knowledge.
2nd
"better wording & description" please feel free to PR. you are welcome to modify/update/add the repo content
